## Data encryption and decryption

* Data Encryption 
        Encryption is a security method in which information is encoded in such a way that only authorized user can read it.it uses encryption algorithm to generate ciphertext that can only be read if decrypted.
        
* Data decryption
          Decryption is a process of taking encoded or encrypted text and converting it back into text that you or the computer can read and understand

* types
        Symmetric (private key):it uses a single key that will be shared among the people who need to receive the message

* Asymmetric(public key):
        Asymmetric encryption uses a pair of public key and a private key to encrypt and decrypt message
        

* Write a function to generate key for encryption

In [4]:
# function  to generate key for encryption
keypath='DataFiles/key.txt'
def generatekey(keypath):
    with open(keypath,'w') as f:
        for i in range(10):
            if i<6:
                f.write(str(i)+' '+str(i+4)+'\n')
            else:
                f.write(str(i)+' '+str(i-6)+'\n')
    return
generatekey(keypath)


In [7]:
# function to decrypt a data File 
keyfile='dataFiles/key.txt'
def dictionarykeyFile(keyfile):
    key={}
    with open(keyfile,'r')as f:
        for line in f:
            line=line.split()
            key[line[0]]=line[1]
    return key
def encryptMarkData(datafile,keyfile):
    #construct a dictionary for a key data
    key=dictionarykeyFile(keyfile)
    with open(datafile,'r')as f:
        filedata=f.read().split('\n')
        with open('DataFiles/encryptedMarks.txt','w')as f:
            for mark in filedata:
                line=''
                for n in mark:
                    line+=key[n]
                f.write(line+'\n')
        return
datafile='DataFiles/marks.txt'
encryptMarkData(datafile,keyfile)

In [10]:
def decryptMarksData(encryptedfile,keyfile):
    key=dictionarykeyFile(keyfile)
    newkey ={}
    for key,value in key.items():
        newkey[value]=key
    with open(encryptedfile,'r')as f:
        encrypteddata=f.read().split("\n")
    with open('DataFiles/decryptedMarks.txt','w')as f:
        for encryptedmark in encrypteddata:
            line=''
            for n in encryptedmark:
                line+=newkey[n]
                f.write(line+'\n')
    return
encryptedfile='DataFiles/encryptedMarks.txt'
import timeit
st=timeit.default_timer()
encryptMarkData(encryptedfile,keyfile)
print(timeit.default_timer()-st)

0.026176163999480195


### numpy arrays

## Python Libraries For Data Science
         Data science is the process of deriving knowledge and insights from a huge and diverse set of data through organizing, processing and analysing the data. It involves many different disciplines like mathematical and statistical modelling, extracting data from it source and applying data visualization techniques. There are nearly 20 python libraries for Data Science. Top five python libraries are
* TensorFlow
* NumPy
* SciPy
* Pandas
* Matplotlib In those libraries, Numpy and Pandas are the first choice to the data scientists who are aware of the technologies.
### NumPy: (Numerical Python)
Numpy is Base N-Dimensional Array Package, is a python library and a fundamental package for scientific computing in Python. It is used to create multidimensional arrays for fast operations. Use the following import conversion. \Ex: >>import numpy as np
### NumPy Arrays
NumPy have a fixed size of arrays used to store a collection of elements, unlike python lists. There are three types of arrays called 1D, 2D and 3D arrays.

## creating 1d and 2d array using numpy

In [1]:
import numpy as np
array_id=np.array([2,4,5,6,7,9])
print(array_id)
print(type(array_id))

[2 4 5 6 7 9]
<class 'numpy.ndarray'>


In [2]:
import numpy as np
array_2d=np.array([[2,3,4,],[5,8,7]])
print(array_2d)

[[2 3 4]
 [5 8 7]]


* program to print the given list into an array using numpy

In [3]:
import numpy as np
li=[1,2,3,'z']
a=np.array(li)
print(a)

['1' '2' '3' 'z']


In [4]:
import numpy as np
li=[1,2,3,'z']
a=np.array(li)
a

array(['1', '2', '3', 'z'], dtype='<U11')

In [5]:
import numpy as np
li=[1,2,3,4,0]
a=np.array(li)
a

array([1, 2, 3, 4, 0])

* for example the following code print 1d array between 1 to 15

In [6]:
import numpy as np
a=np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [7]:
import numpy as np
a=np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

* for example, the following code print 1000 numbers ina 1d array

In [9]:
import numpy as np
a2=np.arange(10000)
a2

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [10]:
a2=np.arange(10000).reshape(100,100)
a2

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [11]:
a2=np.arange(10000).reshape(100,100)
print(a2)

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


 * create a 2d array and inspect size,shape,dimensions and dtype of the array

### Inspect the structure and Content of array using “ndarrays”
* The most basic object in NumPy is the “ndarray” object or simply an “array”.
* The ndarray has important attributes. They are
    * ndarray.ndim: No of dimensions of array referred as “rank”.
    * ndarray.shape: Returns the length of the array in tuple.
    * ndarray.size: Returns the size of an array.
    * ndarray.dtype: We can create or specify “dtype” using standard Python types. NumPy provides            types like numpy.int32, numpy.int16, and numpy.float64
    * ndarray.itemsize: Returns the size in bytes of each element in an array
#### Create a 2D Array and inspect size, shape, dimensions and dtype of the array.

In [13]:
import numpy as p
array1=np.random.randint(0,2,size=(3,3))
array1[2][2]
print('shape',array1.shape)
print('size:',array1.size)
print('dtype:',array1.dtype)
print('Itemsize:',array1.itemsize)
print('data:',array1.data)
array1

shape (3, 3)
size: 9
dtype: int32
Itemsize: 4
data: <memory at 0x0000022765007990>


array([[1, 0, 0],
       [1, 1, 0],
       [0, 0, 0]])

In [14]:
array1=[[1,2,3,4],[5,6,7,8]]
a1=np.array(array1)
a1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
print("shape:",a1.shape)
print("data type:",a1.dtype)
print("size:",a1.size)


shape: (2, 4)
data type: int32
size: 8


In [19]:
import numpy as np
arr=np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

* reverse the array using slicing

In [20]:
arr[::-1]

array([[10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

* create a an array of 1's.Take a list & convert it into a #d array and add 1 to each element ina an array

In [25]:
np.ones?

In [21]:
import numpy as np
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [23]:
b=[[1,2,3],[10,20,30],[11,22,33]]
c=np.array(b)
c

array([[ 1,  2,  3],
       [10, 20, 30],
       [11, 22, 33]])

In [24]:
d=c+1
d


array([[ 2,  3,  4],
       [11, 21, 31],
       [12, 23, 34]])

* we can perform arithmetic operators in numpy like addition,subtraction etc.,also log sin cos

In [27]:
a=np.arange(1,7).reshape(2,3)
b=np.arange(5,11).reshape(2,3)
print(a,)
print(b,'\n')
print(a+b)
print(a/b)

[[1 2 3]
 [4 5 6]]
[[ 5  6  7]
 [ 8  9 10]] 

[[ 6  8 10]
 [12 14 16]]


In [28]:
a=[1,2,3]
a1=np.array(a)
print(np.sqrt(a1))
print(np.sin(a1))
print(np.cos(a1))
print(np.log(a1))

[1.         1.41421356 1.73205081]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[0.         0.69314718 1.09861229]
